version: "2"
services:
  web:
    env_file:
      - .env    
    build: .
    command: nodemon -L --inspect=0.0.0.0:5858
    volumes:
      - .:/code
    ports:
      - "${API_PORT}:${API_PORT}"
      - "5858:5858"
